project:
  type: website
  
execute:
  freeze: auto

website:
  page-navigation: true
  title: "MAT 212 - Winter 2025"
  description: "Homepage for MAT 212 - Multiple Regression Analysis at the College of Idaho, Winter 2025"
  site-url: https://mat212wi25.netlify.app/
  
  repo-url: https://github.com/EricFriedlander/MAT212WI25
  repo-actions: [edit, issue]
  
  page-footer:
    background: "#412d5e"
    left: |
      &copy; Copyright 2025, Eric Friedlander
    right: |
      This site is built with [Quarto](https://quarto.org/)
      
  sidebar:
    background: "#bbbbbb"
    logo: "images/logo.png"
    align: center
    tools: 
      - icon: code-square
        href: https://rstudio.collegeofidaho.edu/
        text: "RStudio"
      - icon: person
        href: https://cofi.instructure.com/courses/17093
        text: "Canvas"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - schedule.qmd
      - syllabus.qmd
      - support.qmd
      - links.qmd
      - section: Computing
        contents: 
        - href: computing-access.qmd
        - href: computing-inferencesummary.qmd
        - href: computing-r-resources.qmd
          text: R resources
      - section: Project
        contents:
        - href: project/project-instructions.qmd
          text: "Instructions"
  
 
format:
  html:
    theme:
      - cosmo
      - theme.scss
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true
    



