project:
  type: website

website:
  page-navigation: true
  title: "MAT 212 - Winter 2025"
  description: "Homepage for MAT 212 - Multiple Regression Analysis at the College of Idaho, Winter 2025"
  site-url: https://mat212wi25.netlify.app/
  
  repo-url: https://github.com/EricFriedlander/MAT212WI25
  repo-actions: [edit, issue]
  
  page-footer:
    background: "#412d5e"
    left: |
      &copy; Copyright 2024, Eric Friedlander
    right: |
      This site is built with [Quarto](https://quarto.org/)
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



